baseURL = "https://abuqi.github.io/study"
languageCode = "zh-CN"
title = "熊爸爸和乐乐的学习角"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "熊爸爸"

[params]
  author = "熊爸爸"
  subtitle = "和孩子一起学习...."
  keywords = "熊爸爸,语文,数学,英语(小学)"
  description = "学习笔记"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
  ## 备案信息
  beian = "辽ICP备19020777号"
  ## 图片放大显示
  fancybox = true

## 友情链接，可以多个

[[params.links]]
  title = "熊爸爸的学校角"
  name = "熊爸爸的学校角"
  url = "https://study.abuqi.site"

## 侧边栏广告位
[[params.ads]]
  title = "【2019双12】ALL IN CLoud 低至1折"
  url = "https://www.aliyun.com/minisite/goods?userCode=nbh6li2s"
  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

[[params.ads]]
  title = "新人福利会场"
  url = "https://www.aliyun.com/1111/new?userCode=nbh6li2s"
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
  
## [[params.ads]]
##   title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
##   url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
##   img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
## [[params.ads]]
##   title = "【渠道专享低折扣】11月特惠 限时2折"
##   url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
##   img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"



## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "document"
    name = "资料"
    url = "/docs/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4